---

- name: Uninstall the existing version of Docker
  apt:
    name: "{{ docker_uninstall_items}}"
    state: absent
    update_cache: yes

- name: Upgrading to the Latest version
  include: "tasks/bes-install.yml"



