---

- name: Ensure Docker is installed and command is running
  command: docker --version
  register: docker_command
  ignore_errors: true

- name: Docker is installed
  debug:
    msg: "{% if docker_command.rc == 0 %} Docker is installed {% else %} Docker Not found {% endif %}"

- name: Ensure /etc/docker/ directory exists.
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_daemon_options.keys() | length > 0

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  ignore_errors: "{{ ansible_check_mode }}"

